### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Hime0698** [DrKylstein/retro-proxy#2]
Following the quick start guide, once I run the last command, I just get this error:

00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

Assistance would be appreciated, this looks like EXACTLY the project I've been hunting for WEEKS, and I'd really like it to work, lol.

**Comment by DrKylstein** [comment]
Unfortunately, there are multiple programs called 'yarn' and the Ubuntu repositories have favored a different one. Their version of the yarn package manager for node is called 'yarnpkg'. Alternatively, you could install npm first, then use npm to install yarn: 'sudo npm install -g yarn'

Edit: looks like the packages are that way in Raspbian too, so it's probably inherited from Debian.
