### ISSUE TITLE
Not viewing SSL content at all

### ISSUE THREAD

**Issue by manuelkamp** [DrKylstein/retro-proxy#4]
If I'm using this proxy, SSL content is not provided at all. For example, a weather image, where the original url is https does not load. I can work around this by setting it to http. But I also implemented a RSS feed reader on my retro-Landingpage and the links there are provided as https. If I open them on Win98SE, (FF 2) only blank pages are shown. However, on the older IE6 it works...?

**Comment by DrKylstein** [comment]
I assume you're talking about embedded images and "link" tags? Can you provide the URL of a page that has this issue?

**Comment by manuelkamp** [comment]
No, I am talking about the whole page content. There is just a blank white page (no html in site source). this is one url for example:  https://www.kleinezeitung.at/steiermark/muerztal/18228543/wie-man-aus-einer-schlosserei-einen-weltkonzern-formt

If I open the url without http, it works, so no DNS issue or something like that. However, it would not be a problem to map https to http, since I embedd this from RSS feed from this newspaper into my retro-intranet webpage, but it kind of does not do what it is supposed to do.

**Comment by DrKylstein** [comment]
The main page URL must be http, the server doesn't respond to https. Most URLs in the page are rewritten to http.

**Comment by DrKylstein** [comment]
It doesn't appear that I can redirect without first having a valid https connection. Trying to force current and future versions of Node to allow deprecated encryption methods is not a battle I want to fight.
