### ISSUE TITLE
Could not find MIME for Buffer <null>

### ISSUE THREAD

**Issue by BigErn77** [DrKylstein/retro-proxy#6]
This error pops up in the logs occasionally:

Error: Could not find MIME for Buffer <null> 

at image-bitmap.js:187:15

Can I just ignore it, or does it indicate a problem?

**Comment by DrKylstein** [comment]
Probably just an image failed to load. If you can find a page that consistently causes it, I can investigate, but I wouldn't say it indicates a problem.

**Comment by BigErn77** [comment]
Here's a URL that consistently produces that "Could not find MIME for Buffer <null>" error:

http://change.org/LetReadersRead

That URL also consistently produces a "startsWith" stack trace, I don't know if I should create a separate issue for it:

TypeError: Cannot read properties of null (reading 'startsWith')
    at retro-proxy/index.js:88:21
    at runMicrotasks (<anonymous>)

**Comment by DrKylstein** [comment]
Fixed in b66d9d1da74a328d381800c9b73b6a13662f40e8 
It was trying to process a SVG image. I haven't found a promising module for rendering those, so for now I'm removing them from pages.
